### ISSUE TITLE
Documentation for behaviour of node_modules with babel config

### ISSUE THREAD

**Issue by brentvatne** [facebook/metro-bundler#30]
**Do you want to request a *feature* or report a *bug*?**

Feature

**What is the current behavior?**

No documentation for potentially confusing behaviour of running babel on node_modules and merging config.

**What is the expected behavior?**

Have some documentation and perhaps a better error message if babel config leading to error came from node_modules.

**Please provide your exact metro-bundler configuration and mention your metro-bundler, node, yarn/npm version and operating system.**

N/A

**More context**

https://twitter.com/notbrent/status/887796674353012736

**Comment by mjesun** [comment]
Hi @brentvatne, I agree this behavior is a bit confusing. Unfortunately we don't have any public docs right now, but this is something we added to our ToDo's. I will keep the task open up until we have something, so that we make sure we don't forget about it.

In the meantime, @ide just created a PR (#31) where he adds a flag for enabling/disabling that behavior. I understand what you are asking is to document and not to disable, but at least I think this could help you. We'd add a follow up on that where we add a better error messaging as well as you suggested :)

**Comment by brentvatne** [comment]
hi @mjesun, yeah this is excellent, I work with @ide at expo.io and we discussed it a bit. thanks
