### ISSUE TITLE
DeltaBunder for?

### ISSUE THREAD

**Issue by Rpeanut** [facebook/metro-bundler#81]
hai, I want to know metro-bundler DeltaBunder modules is used for? beacuse i upgrade rn to 0.49.0, i was used rn with 0.45.1 version, i modify some code fit my demand（code split）, in 0.49.0 version  
i find DeltaBunder modules, i want to know used for?

**Comment by Rpeanut** [comment]
@jeanlauliac

**Comment by jeanlauliac** [comment]
Hello @Rpeanut I'm not sure I understand your question. Are you asking what are the new files related to "DeltaBundler" on the `metro-bundler` repository, or do you mean that these files are included in the bundle generated by `metro-bundler`? (That would not be expected.)

Anyhow the DeltaBundler files are a new implementation of the bundling step that is faster and more consistent than the previous implementation in `Bundler` and `Resolver`. We hope to ship it for OSS in some mid future.

**Comment by Rpeanut** [comment]
@jeanlauliac  thank you very much !!!  Would you consider code split(after all Rn and React source code are so big)

**Comment by jeanlauliac** [comment]
Yes we're considering how code splitting (or "bundle splitting") would fit into the model! :)  Not sure of the timeline just yet however.

**Comment by rafeca** [comment]
Hey @Rpeanut, last week we released version `0.21.0` of metro, which already uses the new bundling logic of the Delta Bundler. The Delta Bundler is able to improve the speed of rebuilds significantly by only doing differential builds, based on the files that were modified since last build.

The next step is to use this new infra to only send "deltas" to the devices, so metro will only send the modified files (instead of the whole bundle) between rebuilds.
